### PR TITLE
ofxGestureGenerator

### PR DESCRIPTION
**Pull request by rsodre**
Hey!!
I've implemented ofxGestureGenerator for simple hand tracking, and just merged with your master branch.
It's well tested and the example is updated.
After the merge I noticed a lot of files were commited but had no changes, like the includes (???)
I'm still taming git!
Cheers!
Roger

### CODE REVIEW

**Comment by gameoverhack** [comment]
Snap!!
I've been working on an ofxGestureGenerator this week as well, but got sidetracked by recompiling the dylibs for mac so that tinyXML/ofXmlSettings works correctly...which I just got happening (hooray)...

I see you've gone ascorbin's route of using a gesture generator to trigger hand tracking...I also went this way, and then noticed that the hand tracking example from Nite uses a Session manager to do the triggering (I think it is essentially the same as the gesture generator, but it handles some of the callbacks differently?)...anyways I'm still exploring that, but you've got further on tracking multiple hands by the look of things...

I also like some of the other changes I see, so I'll start merging our code...I too am pretty fresh to git, so bear with me while i get the hang of it (hence some redundant commits, etc)...

M

**Comment by rsodre** [comment]
Hello!

The code is ready for multiple hands but it's only tracking one hand.
Basically, every hand movement triggers a gesture, even the hand already being tracked.
There must be a way to ignore it, but I couldn't find how.
I just copied some code that was already working, so I really don't know what's happening under the hood.

Anyway, i hope it helps!

Roger

**Comment by gameoverhack** [comment]
Hey Roger

Pulled your changes to my develop and experimental branches, then I seperated ofxGestureGenerator and ofxHandGenerator on my experimental branch.

I added multiple hands to both develop and experimental....

That is:
my master : no gesture or hand tracking (just updated newly compile libs)
my develop : merge of our methods for ofxHandGenerator + multiple hands working
my experimental : merge and then seperation into ofxHandGenerator and ofxGestureGenerator (using ofEvents) + multiple hands working + more smoothing options (both openni and custom) 

Can you have a look and test?

**Comment by rsodre** [comment]
Hey!
That was fast!
Ok, I'll try it.
Thanks!

**Comment by gameoverhack** [comment]
Hey R

Just pushed hardware auxiliary drivers to the experimental branch as well...Motor, LEDs, Accelerometer

;-)

**Comment by rsodre** [comment]
Hey!!!

I was testing your experimental branch and I like it!
Specially the multiple hands and hardware control.
I already moved on to other things, it may take a few days since I get back to Kinect dev.
My only suggestion is to apply the same hands filter to accelerometer.

Thanks!!
Roger

**Pull request closed without merging**
